// File generated by Antigravity - Manual Firebase Configuration
// To update, run `flutterfire configure` if you have CLI installed.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you are using the manual Antigravity configuration.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you are using the manual Antigravity configuration.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you are using the manual Antigravity configuration.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you are using the manual Antigravity configuration.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTQXu00pKUE19ZMIzoHlMsCpNWFwyLqY0',
    appId: '1:129465119098:android:2a53e8f981b9537f0366c3',
    messagingSenderId: '129465119098',
    projectId: 'helmove',
    storageBucket: 'helmove.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4HBBnnMDg5Cs6xYvStRguk3Xuv7UFMQ',
    appId: '1:129465119098:ios:65dad8ac33ca810d0366c3',
    messagingSenderId: '129465119098',
    projectId: 'helmove',
    storageBucket: 'helmove.firebasestorage.app',
    iosBundleId: 'com.helmove.app',
  );
}
